### ISSUE TITLE
Messages: messages_controller message type ohne constantize

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito_cvp#100]
type wie bei events im model zurück geben:

https://github.com/hitobito/hitobito/blob/master/app/controllers/events_controller.rb#L99

wir wollen so verhindern das ein constantize auf irgend ein type mitgegeben und in eine class umgewandelt wird.
ausserdem grundsätzlich gleich machen wie bei events

**Comment by amaierhofer** [comment]
Ist aus meiner Sicht nicht notwendig, es wird ohnehin sichergestellt, dass nur Klassen vom Typ `Message` tatsächlich verarbeitet werden.

**Comment by psunix** [comment]
@amaierhofer auch nicht damit es gleich gemacht wird wie im events controller? 
der aufwand ist ja nicht gross das umzustellen.
