### ISSUE TITLE
Post Verzeichnis importieren

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_cvp#17]
- [x]  Post [PLZ Verzeichnis](https://service.post.ch/zopa/dlc/app/?lang=de&service=dlc-web#/main) einlesen und in einfaches cvs files (Zips, Addressen, Nummern) überführen,  [Doku](https://github.com/hitobito/hitobito_cvp/files/5398169/Street_directory_with_sorting_data.pdf)
- [x] Vereinfachte CVS files aggregieren und in Adressen überführen
- [x] Adressen in neuer Tabelle addresses (street_name, zip, numbers) ablegen
- [x] Sämtliche Address Felder importieren
- [x] Überprüfung der nicht zuordenbaren Adressen der CVP gegen das Postverzeichnis
- [x] Ggf. weitere Datensätze (Gebäude) aus Postfile als Adresse importieren

**Comment by olibrian** [comment]
Passt das Addressverzeichnis der Post für hitobito?
Alternative:
* Open Street Map API (https://nominatim.openstreetmap.org/)
* Swisscom Directory Service

**Comment by amaierhofer** [comment]
Im aktuellen Verzeichnis der Post finde ich in etwa 90% der direkt auf den KontaktDaten hinterlegten Strassennamen. Ca 4000 Adressen werden nicht gefunden, dabei habe ich den Eindruck das deutschsprachige, italienische und französische Adressen in etwa gleich verteilt sind.

Das Service der Swisscom bietet kein API sondern Batch Verarbeitung über SFTP. Somit ist keine unmittelbare Validierung oder Adresse Vorschlag mit diesem Service möglich.

**Comment by amaierhofer** [comment]
In etwa 4% der Addressen aus der aktuellen Datenbank sind ungültig
