### ISSUE TITLE
F02-15 Beim erfassen Adressenvervollständigung vornehmen (Ajax) 

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_cvp#18]
Im Ideallfall kann das mit Stimulus implementiert werden, Fortschritt Stimulus / Webpacker siehe hitobito/hitobito#996
- Neuer Controller der Address Struktur (zip, street, number) versteht
- onChange vom Feld (Address) entsprechende Einträge suchen und zurückliefern "Belpstrasse 36, 3005, Bern"
- Falls Eintrag ausgewählt wird, restliche Felder abfüllen
- Eingabe von ungültigen Addressen soll möglich sein

**Comment by ninfaj** [comment]
Eine erste Idee:
Bei der Eingabe der Adresse werden dem Benutzer gleich die gefunden Adressen vorgeschlagen. Wenn er eine auswählt, werden die anderen Felder ausgefüllt.
![image](https://user-images.githubusercontent.com/157533/94282072-b311aa00-ff4f-11ea-81fb-8d4c3470bd3c.png)

**Comment by TheWalkingLeek** [comment]
Closed in https://github.com/hitobito/hitobito/pull/1087
