### ISSUE TITLE
 F04-03 Anbindung an Druckerei (Suter & Gerteis AG)

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_cvp#26]
**Aktuell mit OM:**
Aktuell erhält die Druckerei ein E-Mail mit einer Auftragsnummer. Auf einem FTP Server von OM steht unter dieser Auftragsnummer ein PDF mit den Briefen zur Verfügung. Die Druckerei nimmt das PDF und druckt dies auf Briefpapier, Einzahlungsvorlagen und falzt die Dokument und kann bei Bedarf auch in CVP Couverts verschicken.

**Soll:**
Die Druckerei ist da recht offen wie sie die Daten erhalten. Was die Druckerei benötigt:
* PDF File (ohne Logo)
* Auftrag
* Empfänger E-Mail als Custom Content

**Möglichkeiten:**
* ~PDF als Mail verschicken (wohl nicht so ideal, da recht gross)~
* ~PDF via hitobito als shared Link zur Verfügung stellen~
   * Generieren on the fly ~oder als Dokument ablegen~
   * Gültigkeit von Link festlegen
   * ~Dokument löschen wenn File abgeholt wurde~
* **Index Seite auf welche die Druckerei zugreifen kann.**
   * Notification als Mail an Druckerei, dass auf der Index Seite neue Druckaufträge zur Verfügung stehen.
   * Druckerei holt Dokument selbständig ab

* ~Auftrag als Text Mail schicken~
* ~Auftrag als per Mail mit Auftrags PDF als Anhang schicken~
~* Auftrag als Mail mit passendem XML als Anhang schicken~

**Noch zu klären**
* Wie können wir den Zugang/Link schützen? -> Basic Auth Login für Controler
* Kann ich als Externer mit den Infos, welche bei Hitobito auf github sind, ein Druckauftrag generieren? -> Der Auftrag kann nur mit Login generiert werden. Per Mail wird nur eine Benachrichtigung, keine Links oder Daten gesendet.

* Was ist alles auf dem Auftragsblatt vorhanden -> bei der Druckerei
* ~Struktur vom XML -> bei der Druckerei~
* Welche Produkte -> CVP Stefan

# Technische Umsetzung

- [ ] Model: Assignment(person_id, title, description, state, attachment_id, attachment_type, created_at, updated_at), alle Felder must, übersetzt als Auftrag, `attachment` ist polymorph, i.d.R wird das eine spezifische `Message` sein, state ein enum -> Ungelesen, Gelesen
- [ ]  Auf Person Profil eigenes Tab mit Aufträge, Auftragsliste vorerst nur `index` und `show`. Separate `new` seite.
- [ ]  Auf der `show` Seite PDF Link zu dem Message Attachment  (`/messages/:id.pdf`)
- [ ] Der Assignment status wird von Neu zu Gelesen geupdated, sobald der adressierte Nutzer das `assignments#show` aufruft.
- [ ] Auf der `new` Seite wird message_id per params übergeben, der Rest im formular gesetzt
- [ ] Im `messages#show` einen "Druckauftrag stellen" Knopf anzeigen, solange der message status "Entwurf" ist. Dieser redirected zum `assignments#new`
- [ ] wird ein neuer Auftrag erstellt, wird der Empfängerperson eine E-Mail gesendet
- [ ] Das E-Mail verwendet ein Template aus CustomContent
- [ ] Druckerei in die production seeds vom CVP Wagon aufnehmen, keine Rolle seeden
- [ ] In den Wagon settings ein `[:assignments][:enabled]` Flag. Wenn false, wird der Assignment Tab und der "Druckauftrag stellen" Knopf ausgeblendet 

# Resultat
- Druckerei kann alle Aufträge auf der eigenen Profilseite einsehen
- Druckerei hat einen eigenen User Entry, Zugang mit E-Mail und Passwort

Die Idee ist das dieses Auftragsmodul später erweitert werden kann. Aufträge für andere Aufgaben wie Drucken; z.B. Reperaturauftrag

**Comment by psunix** [comment]
![cvp_drucken](https://user-images.githubusercontent.com/655627/102754380-32572400-436d-11eb-86b2-c18a511cdb6f.png)

**Comment by TheWalkingLeek** [comment]
Implemented in https://github.com/hitobito/hitobito/commit/428080fb9b845d463e29bc05a70367ab57f39749
