### ISSUE TITLE
Organisationsstruktur abbilden

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_cvp#3]
Siehe dazu https://github.com/hitobito/hitobito/blob/master/doc/architecture/08_konzepte.md

- [x] Ebenen, Gruppen und Untergruppen definieren
- [x] Je Gruppe entsprechende Rollen und Permissions definieren
- [x] Seed Daten ergänzen
- [x] Gruppen / Rollen / Permissions  mit Kunden gegenchecken
- [x] Kunde bildet auf Integration einen Teilbaum ab und gibt Feedback

**Comment by olibrian** [comment]
Epic #5
