### ISSUE TITLE
F04-16 Mailchimp bounces integrieren, Personen markieren (tag email:invalid)

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_cvp#31]
Ziel
- [ ] Personen, welche eine unzustellbare Mail haben erhalten das tag `email:invalid`
- [ ] Fehlerhafte Mailadresse wird im GUI gekennzeichnet. Es kann auf einer Person mehrere Mailadressen haben
- [ ] Fehlerhafte Mails werden in Abos nicht berücksichtigt.
- [ ] Fehlerhafte Mails werden nicht nach Mailchimp synchronisiert

**Comment by amaierhofer** [comment]
Siehe https://github.com/hitobito/hitobito/pull/1080
