### ISSUE TITLE
F08-01 Abacus

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_cvp#42]
Definiertes XML Export für Abacus

Informationen zu erzeugten Rechnungen/Mahnungen werden über eine geeignete Schnittstelle an das Buchhaltungssystem Abacus übertragen.

Weitere Infos zu Abacus https://github.com/hitobito/hitobito/issues/598

**Comment by ZuegerCVP** [comment]
Wie genau wir diese Schnittstelle machen muss ich mit der Finanzverantwortlichen und unserem Treuhänder klären.
Momentan ist es so, dass unser System jeden Monat einmal ein Dokument generiert, wo die Finanzbewegungen pro Konto abgebildet sind. Dieses wird automatisch an die entsprechende Person verschickt die Finanzkontrolle im System hat. 
Damit können die Finanzverantwortlichen die Bewegungen in die eigene Buchhaltung übertragen. Wie genau und ob wir eine Schnittstelle zu Abacus brauchen müssen wir anschauen. Ich bin froh, wenn ihr mir aufzeigen könnt, was ihr genau wissen müsst, dann kann ich mit unseren Finanzverantwortlichen sprechen und alle Details nachfragen.

**Comment by olibrian** [comment]
Gemäss Meeting vom 05.11.2020 ist dies kein Thema.
