### ISSUE TITLE
Gruppieren von Rechnungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_cvp#54]
Ziel: Rechnungen (z.b. Mitgliederbeiträge) sollen an gewisse Gruppen erstellt werden können. Diese werden via Filter ausgewählt. Nach der entsprechenden Selektion wird die Rechnung erstellt. Falls unterschiedliche Rechnungsbeträge (z.b. Passiv und Aktivmitgliedschaften) gestellt werden, wird dies in zwei separaten Schritten gemacht. Die Rechnungen sollen gruppiert dargestellt werden. So, dass beispielsweise nachvollzogen werden kann, welcher Rechnungsbetrag noch offen ist und welcher bereits bezahlt wurde.

# Lösungsvorschlag
* Filter auf den Rechnungen ist bereits vorhanden. Ermöglicht das Filtern nach Text, Status, und Termin.
* Pagination von 50 auf den Rechnungen einführen.
* Abhängig vom gewählten Filter werden nur die entsprechenden Total pro Stati angezeigt. Wenn alle Rechnungen angezeigt sind, wird pro Stati ein Total angezeigt.

![hit_cvp_rechnungen](https://user-images.githubusercontent.com/655627/94424623-ceb4c480-018a-11eb-988c-df5c737f4602.png)

**Comment by ninfaj** [comment]
Folgende Punkte sind mir aufgefallen:

- Es gibt vor der Tabelle mit den Rechnungen sehr viele verschiedene Elemente: (Suche / Filter, Aktionen, Auswahl Jahr, Pagination, Statistik) --> würde es da Sinn machen sich dazu mal generell Gedanken zu machen? (das ist vermutlich bei anderen Views ähnlich)
- Die Status erhalten durch die farbigen Labels sehr viel Gewicht. Allenfalls könnte man die Farben etwas unauffälliger darstellen, z.B so

![image](https://user-images.githubusercontent.com/157533/94899493-b9de7680-0493-11eb-95ae-9a2d8f09b0ce.png)

**Comment by amaierhofer** [comment]
Folgendes Vorgehen wurde implementiert 

- [x] Neuer Menüpunkt Sammelrechnungen unter Rechnungen
- [x] Anzeige der Aggregierten Zahlen (Empfänger, Beträge) auf der Sammelrechnung
- [x] Automatischer abgleich dieser Zahlen beim Anlegen neuer Zahlungen (UI oder XML import)
- [x] Von der Sammelrechnungen kann zu den dazugehörigen Rechnungen navigiert werden
- [x] Rechnungen können gestellt und verschickt werden, navigation zurück zu Sammelrechnung
- [x] Sammelrechnungen können von Abos aus erstellt werden

Folgender Punkt noch offen 
- [ ] Invoice Sheet anpassen wenn Rechnungen einer Sammelrechnung betrachtet werden (Darstellung analog Group>Person) 
- [ ] Verifizieren des Zahlungsprozesses
- [ ] Verifizieren vom Job verhalten (bei Sammelrechnung von 100 Empfängern bis 100.000 Empfängern)
