### ISSUE TITLE
Anpassung an Gruppenstruktur

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_cvp#57]
Gemäss Feedback aus dem Chat
>  Liebe alle, ich habe ein paar Anpassungen an die Struktur:
> 1. Ändern wir den Vorstand in Parteigremium auf allen Ebenen; überall sollte es die Rollen: Präsident, Leitung, Mitglied, Gast geben
> 2. Auf Ebene Bund brauchen wir die Rolle Mitgliede und Sympatisant wie bei den unteren Ebenen, Grundsätzlich wäre es gut, wenn ein Mitglied in einer Ortspartei automatisch Mitglied aller darüberliegenden Ebenen ist (Region, Kanton und Bund)
> 3. Wir ändern das bestehende Parteigremium zu Arbeitsgruppe, auch hier mit den Rollen: Präsident, Leitung, Mitglied, Gast
> 4. Kontakte ändern wir zu Externe Kontakte.
> 5. Bei den Rollen der Gerichte auf Kantonaler Ebene ändern wir die obere Instanz zu zweite Instanz
> 6. Auf Kantonaler Ebene beim Präsidium die Rolle Gast hinzufügen
> 7. In den Regionen nehmen wir die Delegierten auf
> 8. Auf Gemeindeebene nehmen wir die Kommissionen weg. Diese sind ja bereits bei den Gewählten abgebildet
> 
> 9. Auf der Gemeindeebene bitte die Rolle Mitglieder weitere Kommissionen zu Mitglieder weitere Gemeindekommissionen ändern
> Ich bin froh, wenn ihr diese änderungen so übernehmt, dann können wir das nochmals durchgehen und allenfalls weitere Details korrigieren.  Vielen Dank euch!

**Comment by ZuegerCVP** [comment]
Passt so für den Moment, wir können dies später nochmals anschauen. Für einen ersten Datenimport wird dies so funktionieren meiner Meinung nach. Danke!
