### ISSUE TITLE
Automatische Mitgliedschaft in allen Ebenen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_cvp#58]
Mitglieder in einer Ortspartei sollen auch Mitglieder in der Region, dem Kanton und im Bund sein. Dies ist implizit dadurch, dass einen Ortspartei ebenfalls an eine Region, einem Kanton und dem Bund angehängt ist bereits gegeben. 

Welche Vor und Nachteile hätte eine automatisch erstellte (und wieder gelöschte) explizite Rolle in den übergeordneten Ebenen. Welches Requirement wird durch die bestehende Filter nicht ausreichend abgedeckt?

**Comment by psunix** [comment]
beim Filter der Personen kann Hitobito heute bereits alle Personen von darunterliegenden Ebenen/Gruppen anzeigen:

![image](https://user-images.githubusercontent.com/655627/94405527-fd25a600-0170-11eb-995f-eebdec690f27.png)

@Stefan Züger gibts es Use Cases die eine Rolle weiter oben rechtfertigen?

**Comment by ZuegerCVP** [comment]
Für uns und für die Kantone wär es sehr schön, wenn die Anzahl Mitglieder/Sympatisanten pro Ebene relativ einfach und schnell angezeigt werden können. Momentan sehe ich, wenn ich die Mitglieder auf der obersten Ebene filtere, nur 2 Mitglieder. 

Ziel wäre es, wenn ich nach Mitgliedern der oberen Ebene filtere alle Mitglieder der unteren Ebenen angezeigt würden. Die Anzahl der Mitglieder ist relevant für die Anzahl Delegierte die ein Kanton hat und für die Beiträge die der Kanton an die Cvp Schweiz zu zahlen hat. Zudem werden wir und die Kantone immerwieder von den Medien gefragt, wie viele Mitglieder vorhanden sind. Aus diesen Gründen wäre es schön dies so einzurichten.

Ebenfalls ist es laut unseren Statuten so, dass ein Mitglied einer Ortspartei automatisch auch Mitglied der Region, des Kantons und bei der Cvp Schweiz ist. Eventuell kann man diese Rollen automatisch zuweisen, wenn jemand neu auf Ebene Ortspartei eingetragen wird?

**Comment by olibrian** [comment]
Aus der Konzeptionsmeeting, 01.10.2020
Wir verzichten auf mehrere Rollen automatisch zu vergeben. Gründe: Komplexität in der Applikation und zusätzliches Regelwerk. 
Lösungsvarianten in Issue #60 und #61 beschrieben.
