### ISSUE TITLE
Definierte Filter auf Personenliste

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_cvp#60]
**Ziel**: 
Eine Übersicht wie viele Mitglieder in der Gruppe sind soll einfach ersichtlich sein. 

**Lösungsvorschlag**:
Anzeigen mit definierten Filtern wie bei der GLP. 

![Screenshot from 2020-10-01 11-02-55](https://user-images.githubusercontent.com/9592347/94940546-ed40f580-04d3-11eb-85e6-a848d3f78db2.png)

Siehe: https://github.com/hitobito/hitobito_glp/issues/9

**Comment by amaierhofer** [comment]
Da die CVP auf den Ebenen selber keine Rollen definiert hat, kann der default Filter "Mitglieder" verwendet werden
