### ISSUE TITLE
Strukturierung der Rolle auf der Person

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_cvp#61]
**Ist:** 
Aktuell werden die Rollen auf der Person View etwas willkürlich dargestellt.

![image](https://user-images.githubusercontent.com/9592347/94941941-e87d4100-04d5-11eb-8dd4-b65f712a6fa8.png)

**Soll:**

Die angezeigten Rollen sollen nach den Layer gruppiert werden. Dabei sollen nur Layer dargestellt werden, in welcher die Person eine Rolle haben. Weiter sollen zusätzliche "automatische" Mitgliedschaften angezeigt werden. Dies wird aber nur auf der Person entsprechend angezeigt und keine effektive Rolle im System vergeben. Diese können aber nicht gelöscht/bearbeitet werden. So ist die Person welche Mitglied in Geiswald ist, automatisch auch Mitglied in St. Gallen und der CVP/PDB/PPD. 

Beispiel:

**CVP/PDB/PPD**
- Mitglied

Sekreatriat
- Mitarbeiter [-]

Konferenz der Partei..
- Mitglied (Mitarbeiter) [-]

**St. Gallen**
- Mitglied

Sekretariat
- Leitung [-]

**Geiswald**
Mitglieder
- Mitglied [-]

**Bern**
- Mitglied

**Burgdorf**
Mitglieder
- Mitglied [-]

**Comment by psunix** [comment]
Input von @ZuegerCVP 

Ich habe eine Frage, soeben habe ich versucht eine Gruppe "Delegierte CVP Schweiz" zu erstellen. Eine solche Gruppe braucht jeder Kanton und auch die Ebene Cvp Schweiz braucht eine solche Gruppe, die am besten über einen Filter automatisch mit den Mitgliedern der Kantonalen Gruppen gefüllt wird. Nun ist dies aktuell nicht möglich, da die Mitglieder ja nicht automatisch auch die Rolle Mitglied bei der Cvp Schweiz haben. Ich kann sie deshalb nicht der Gruppe der Delegierten hinzufügen, ich glaube wir haben letzte Woche besprochen, dass alle mit der Rolle Mitglied auf Ortsebene auch Mitglieder bei der Region dem Kanton und der CVP Schweiz werden oder? Es wäre super, wenn ihr mich informieren könnt, wenn diese Anpassung gemacht wurde, dann kann ich Testen, wie das mit den Delegierten funktionieren wird.

**Comment by olibrian** [comment]
Als Alternative Idee:
Geiswald
Mitglieder

    Mitglied [-], Mitglied St. Gallen, Mitglied Schweiz

**Comment by amaierhofer** [comment]
Ersetzt durch #62
