### ISSUE TITLE
Merkmale die nicht auf den Gruppentyp passen 

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_cvp#74]
Für bestimmte Merkmale (Nationalrat, Bundesrat, Ständerat, Richter, Kantons Sekretär, Kantons Präsident) sollen in die entsprechenden Gruppe gemapped werden. Im Quellsystem sind diese Merkmale oft auf den Ortsgruppe (oder sonstigen Gruppen nicht automatisch auf die Zielgruppe gemapped werden hinterlegt). Die Zielgruppen im Hitobito sollen, falls sie nicht existieren angelegt werden.

- [ ] Für Merkmale die Gruppen ohne Rollen zugeordnet sind (zb `Praesident` in `Group::Ort`) muss die Rolle in die entsprechenden Untergruppe erstellt werden zb. `Ort::Parteigremium::Praesident`

- [ ] Für Merkmale, die Gruppen zugeordnet sind wo keine entsprechende Rolle existiert (zb. `Kantonsrat` in `Ort::Praesidium`) muss die Rolle in einer anderen Gruppe angelegt werden. Stefan liefert hier noch eine Liste

**Comment by olibrian** [comment]
Wird durch #89 gelöst.
