### ISSUE TITLE
Empfänger als Abo

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_cvp#76]
Gruppen, die nur aus Personen mit Merkmal Empfänger bestehen, sollen als Abo abgebildet werden. Dabei werden die Empfänger mit einzelnen Subscriptions hinzugefügt.

Überlegen wie wir damit umgehen, wenn in einer Gruppe nich nur das Merkmal Empfänger vorkommt, wir das dann auch ein Abo?

**Comment by olibrian** [comment]
**Ausgangslage:**
Aus der Datenmigration wurden die Empfänger von einem Abo in eine Gruppe hinzugefügt.

**Ziel:**
Die Abos sollen nicht einzelne Empfänger haben, sondern sich an den Rollen in hitobito orientieren. Der Abonomentenkreis soll nicht kleiner werden.

**Umsetzung:**
Auf den Layern (CVP Schweiz, Kantone, Ortsgruppen) werden manuell die benötigten Abos erstellt. Beispiel für die Newsletter oder Versände (Die Politik).
In diesem Abos kann definiert werden, welche Rollen die Abos empfangen können. Weitere Einstellungen wie beispielsweise ob sich jemand vom Abo abmelden kann oder selber anmelden können konfiguriert werden.
Zusätzlich wir die Gruppe mit den migrierten Daten als Empfänger definiert.
Falls sich eine Person aufgrund verschiedenen Rollen im Abo vorkommt, erhält diese Person den Newsletter trotzdem nur einmalig.

**Bereinigung:**
Durch die Duplikatserkennungsfunktion können doppelte Einträge zusammengeführt werden.
Die Gruppen welche migriert wurden können anschliessend manuell bereinigt werden. 
Falls eine Person aufgrund einer Rolle des definierten Abos Empfägner ist, kann die Rolle in der migrierten Gruppe entfernt werden.

**Comment by olibrian** [comment]
Abos werden von der CVP entsprechend dem Vorschlag https://github.com/hitobito/hitobito_cvp/issues/76#issuecomment-756616654 umgesetzt.
