### ISSUE TITLE
Weiter anpassungen an der Gruppen Struktur

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_cvp#80]
Gemäss Absprache mit Stefan werden die Anpassungen aus folgendem XSL übernommen
[Migration_OM_hitobito_ama.xlsx](https://github.com/hitobito/hitobito_cvp/files/5776854/Migration_OM_hitobito_ama.xlsx)

**Comment by amaierhofer** [comment]
Aktualisierte Liste
[Migration_OM_hitobito_ama_aktualisiert.xlsx](https://github.com/hitobito/hitobito_cvp/files/5777281/Migration_OM_hitobito_ama_aktualisiert.xlsx)

**Comment by ZuegerCVP** [comment]
@amaierhofer  
Habe die Liste angeschaut. Kurz:
Zeile 3: Externe Kontakte stimmt
Zeile 18: schaue ich mir noch genau an
Zeile 22: Ja auch im Kanton ZG
Zeile 23: Mitarbeiter statt Mitglied
Zeile 64: Können wir auch so belassen, die Gruppe gibt es sowieso nicht mehr lange, da aufgelöst.
Zeile 68: Der Parteivorstand hat nicht in allen Kantonen dieselbe Funktion. 

Vielen Dank!
