### ISSUE TITLE
Message Model

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_cvp#84]
![htbt-msgs](https://user-images.githubusercontent.com/655627/100749616-34206e00-33e5-11eb-9ecd-34c5c779432d.jpeg)
(Maillog unten links sollte eigentlich MailingList heissen)

_Originally posted by @psunix in https://github.com/hitobito/hitobito_cvp/issues/34#issuecomment-736566575_

**Comment by amaierhofer** [comment]
Leichte Anpassung am Model

- Message (STI Model) für Brief, Brief mit Rechnung, Sms, MailLog
- MessageDispatch (Versand),  Anzahl Empfänger, Begin / Ende vom Versand
- MessageReciept (Empfangsbestätigung) Message wurde an Persons ausgeliefert 

![messages](https://user-images.githubusercontent.com/180780/104178622-f3b40700-540a-11eb-8410-defc528f9ae6.png)
