### ISSUE TITLE
Briefe erstellen und Anzeigen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_cvp#85]
Von der MailingListe aus neue Briefe erstellen und Anzeigen.

- Erstellen und Anzeigen von Briefen
- Einfache Vorschau Funktion  (Empfänger als ID übergeben)
- Ausfüllen von Platzhalter im Brief
- Einfacher BriefKopf mit Absender und Logo aus den Settings

**Comment by olibrian** [comment]
Danke für die Implementation. Erste kleine Rückmeldungen:

- [ ] Preview in einem neuen Tab öffnen
- [ ] Zusätzliche Platzhalter Salutation
- [ ] Absatz: In meinen Tests wurde mir nicht ganz klar, wann eine neue Zeile und wann ein neuer Abschnitt generiert wird. Mögliche Umsetzung: Eine Zeilenumbruch -> neue Zeile (`br`), Zwei Zeilenumbrüche neuer Absatz (`p`)
- [ ] Möglichkeit ein Bild (z.b. Unterschrift) einzufügen
- [ ] Beim Click auf ein Platzhalter dieser im Text einfügen. War beim Preview von Carlo bereits vorhanden.

**Comment by carlobeltrame** [comment]
Korrektur: Die Preview in einem neuen Tab sowie der zusätzliche Platzhalter `salutation` waren bei meiner Demo bereits vorhanden. Klickbare Platzhalter hingegen noch nicht.
