### ISSUE TITLE
Briefe mit Sammelrechnungen integrieren

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_cvp#87]
- neues Message Model `Message::LetterWithInvoice`
- Rechnungsartikel auf der Message integrieren
- PDF Rendering anpassen, sodass Einzahlungsschein mit Brief als PDF generiert wird 
- Rechnungen erst im DispatchJob erstellen

**Comment by olibrian** [comment]
- [ ] Der eigentliche Brief wird auf der Rechnung nicht angezeigt.
- [ ] Auf der Person funktioniert das Log zur Zeit nicht mehr: https://htbt-cvp-prod.appuioapp.ch/groups/22/people/39902/log
- [ ] Reihenfolge der Tabs auf der Person anpassen: Nachrichten zwischen Abos und Rechnungen
