### ISSUE TITLE
Brief PDF Darstellung

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_cvp#88]
Noch festlegen was genau notwendig ist und was eventuell noch auf der Gruppe konfiguriert werden muss. 

Minmal Briefkopf mit 
- Absender Adresse
- Empfänger Adresse

**Comment by olibrian** [comment]
Empfänger entsprechend vorhanden. Weitere Darstellung siehe https://github.com/hitobito/hitobito_cvp/issues/24
