### ISSUE TITLE
Erstellen der Sammelrechnung und Einzelrechnungen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_cvp#90]
- InvoiceList erstellen
- Invoices erstellen
- Invoice mit MessageRecipients verhängen
- counts auf InvoiceList und Message aktualisieren

**Comment by olibrian** [comment]
Rechnung wird korrekt erstellt. Jedoch werden die Mails nicht verschickt, landen zumindest nicht bei Mailtrap. Getestet mit: https://htbt-cvp-prod.appuioapp.ch/groups/1/invoice_lists/1/invoices

**Comment by olibrian** [comment]
Habe die Mails gefunden. Danke.
