### ISSUE TITLE
 Salutation Platzhalter hinzufügen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_cvp#91]
- Feld ist bereits im CVP Wagon
- Label implementierung scheint noch zu fehlen, kann von PBS übernommen werden
- Salutation als Platzhalter auf dem Brief vom cvp wagon aus hinzufügen

**Comment by carlobeltrame** [comment]
@TheWalkingLeek hat schon eine Domain-Klasse `Salutation` im CVP-Wagon erstellt die dasselbe und mehr können sollte wie die Label Implementierung bei der PBS. Aber die Klasse wird noch nirgends verwendet und funktioniert leider auch noch nicht ganz so wie sie sollte.
